# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
trigger:
- master
pool:
  vmImage: 'windows-latest'
variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  disable.coverage.autogenerate: 'true'
steps:
- task: NuGetToolInstaller@1
- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
- task: VSBuild@1
  inputs:
    solution: '**\*.sln'
    createLogFile: true
    
- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\bin\$(buildConfiguration)\net5.0\*tests*.dll
      !**\obj\**
      !**\xunit.runner.visualstudio.testadapter.dll
      !**\xunit.runner.visualstudio.dotnetcore.testadapter.dll
    searchFolder: '$(System.DefaultWorkingDirectory)'
    vsTestVersion: '16.0'
    runTestsInIsolation: true
    codeCoverageEnabled: true
    diagnosticsEnabled: true
    collectDumpOn: 'always'
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '**\bin\$(buildConfiguration)\net5.0\*cobertura.xml'
    reportDirectory: '**\bin\$(buildConfiguration)\net5.0\'
- task: AzureDevTestLabsCreateVM@3
  inputs:
    azureSubscription: 'Visual Studio Professional Subscription (e94871f6-4f7c-43c5-b99d-666960b844db)'
    LabId: '/subscriptions/e94871f6-4f7c-43c5-b99d-666960b844db/resourcegroups/adventure-works-rg/providers/microsoft.devtestlab/labs/hr-production-lab'
    VirtualMachineName: 'amanbekbavla001'
    TemplateFile: 'amanbekbavla001.json'
    FailOnArtifactError: true
- task: PublishBuildArtifacts@1